name: twitter
author: sh4869 <nobuk4869@gmail.com> # name <email>
homepage: https://github.com/sh4869/twitter.dart # https://github.com/user/repo
version: 0.2.0+1
environment:
  sdk: '>=1.0.0 <2.0.0'
description: Twitter API Library
dependencies:
  oauth:
    git:
      url: git://github.com/sh4869/oauth.dart.git
      ref: random-secure
  http: '>=0.11.2 <0.12.0'
dev_dependencies:
  test: '>=0.12.3+6 <0.13.0'
